const DB="nailVaultDB",STORE="images";let db,library=[],editId=null,favoritesOnly=false;
const opts={shape:["Almond","Coffin"],length:["6 mm","7 mm","8 mm"],color:["Pink","Nude","Gold","Red","White","Blue","Green","Purple","Yellow","Black","Mixed"],design:["Floral","French","Gems","Chrome","Cat-eye","Swirls","Abstract","Encapsulation","3D","Luxury","Mixed"],vibe:["Luxury","Glam","Elegant","Playful Glam","Minimal Luxe","Bold"],season:["Year-round","Spring","Summer","Fall","Winter"]};
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=e=>e.target.result.createObjectStore(STORE,{keyPath:"id",autoIncrement:true});r.onsuccess=e=>{db=e.target.result;res()};r.onerror=()=>rej(r.error)})}
function os(mode="readonly"){return db.transaction(STORE,mode).objectStore(STORE)}
function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function refresh(){library=await req(os().getAll());render()}
function render(){let v=favoritesOnly?library.filter(x=>x.favorite):library;count.textContent=`${library.length} images • ${library.filter(x=>x.favorite).length} favorites`;grid.innerHTML=v.length?v.map(x=>{let t=Object.values(x.tags||{}).flatMap(a=>Array.isArray(a)?a:[a]).filter(Boolean);return `<div class="tile"><button class="heart" data-a="fav" data-id="${x.id}">${x.favorite?"❤️":"♡"}</button><img src="${URL.createObjectURL(x.blob)}"><div class="tileBody"><b>Nail Set</b><div class="tileTags">${t.length?t.join(" • "):"Not tagged yet"}</div><div class="tileActions"><button class="dark" data-a="tag" data-id="${x.id}">🏷️ Tag</button><button class="danger" data-a="del" data-id="${x.id}">Delete</button></div></div></div>`}).join(""):'<div class="empty">No photos to show yet.</div>'}
function item(id){return library.find(x=>x.id===+id)}
function openModal(id){editId=+id;let x=item(id);preview.src=URL.createObjectURL(x.blob);let defs=[["shape","Shape","single"],["length","Length","single"],["color","Colors","multi"],["design","Design","multi"],["vibe","Vibe","multi"],["season","Season","multi"]];tagForm.innerHTML=defs.map(([k,t,type])=>{let s=x.tags?.[k]||(type==="multi"?[]:"");return `<div class="tagSec"><h3>${t}</h3><div class="choices">${opts[k].map(v=>`<button class="choice ${(type==="multi"?s.includes(v):s===v)?"selected":""}" data-k="${k}" data-type="${type}" data-v="${v}">${v}</button>`).join("")}</div></div>`}).join("");modal.classList.add("open")}
function closeModal(){modal.classList.remove("open");editId=null}
function filters(){return {shape:shape.value,color:color.value,design:design.value,vibe:vibe.value,season:season.value}}
function match(x,f){return Object.entries(f).every(([k,w])=>w==="Any"||(Array.isArray(x.tags?.[k])?x.tags[k].includes(w):x.tags?.[k]===w))}
function random(use=true){let pool=use?library.filter(x=>match(x,filters())):library;if(!pool.length){alert("No matching photos yet.");return}let x=pool[Math.floor(Math.random()*pool.length)];result.innerHTML=`<img src="${URL.createObjectURL(x.blob)}">`}
photos.onchange=async e=>{for(let f of e.target.files)if(f.type.startsWith("image/"))await req(os("readwrite").add({blob:f,favorite:false,tags:{shape:"",length:"",color:[],design:[],vibe:[],season:[]}}));photos.value="";await refresh()}
grid.onclick=async e=>{let b=e.target.closest("button[data-a]");if(!b)return;let x=item(b.dataset.id);if(b.dataset.a==="tag")openModal(x.id);if(b.dataset.a==="fav"){x.favorite=!x.favorite;await req(os("readwrite").put(x));await refresh()}if(b.dataset.a==="del"&&confirm("Delete this photo?")){await req(os("readwrite").delete(x.id));await refresh()}}
tagForm.onclick=e=>{let b=e.target.closest(".choice");if(!b)return;if(b.dataset.type==="single"){document.querySelectorAll(`[data-k="${b.dataset.k}"]`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")}else b.classList.toggle("selected")}
save.onclick=async()=>{let x=item(editId),tags={};document.querySelectorAll(".tagSec").forEach(s=>{let bs=[...s.querySelectorAll(".choice")],k=bs[0].dataset.k,type=bs[0].dataset.type,a=bs.filter(b=>b.classList.contains("selected")).map(b=>b.dataset.v);tags[k]=type==="multi"?a:(a[0]||"")});x.tags=tags;await req(os("readwrite").put(x));await refresh();closeModal()}
close.onclick=cancel.onclick=closeModal;random.onclick=()=>randomize(true);lucky.onclick=()=>randomize(false);
function randomize(use){random(use)}
favs.onclick=()=>{favoritesOnly=!favoritesOnly;favs.textContent=favoritesOnly?"♥ Showing Favorites":"♡ Favorites";render()}
clear.onclick=async()=>{if(confirm("Delete the entire library?")){await req(os("readwrite").clear());await refresh()}}
reset.onclick=()=>document.querySelectorAll(".filters select").forEach(s=>s.value="Any");
(async()=>{["shape","color","design","vibe","season"].forEach(k=>document.getElementById(k).innerHTML=["Any",...opts[k]].map(v=>`<option>${v}</option>`).join(""));await openDB();await refresh();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{})})()